reanahub/pytest-reana

.gitignore, .travis.yml, MANIFEST.in, README.rst, docs/conf.py, pytest.ini, reana_pytest_commons/__init__.py, reana_pytest_commons/version.py, run-tests.sh, setup.cfg, setup.py, tests/conftest.py, tests/test_version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> docs: REANA-Pytest-Commons camelcase

pytest_reana/fixtures.py, pytest_reana/version.py, setup.py
=> installation: bump reana-db

pytest_reana/version.py
=> release: 0.4.0.dev20181105

setup.py
* Updates reana-commons to 0.4.0.dev20181105.
=> setup: update reana-commons version

AUTHORS.rst, CHANGES.rst, README.rst, pytest_reana/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> release: v0.4.0

CHANGES.rst, README.rst, pytest_reana/version.py
=> release: 0.4.1

pytest_reana/fixtures.py, pytest_reana/version.py
* Modifies the sample_workflow_workspace fixture to have a
parametrized path.
Connects https://github.com/reanahub/reana-client/issues/193
=> fixtures: sample_workflow_workspace with path

pytest_reana/fixtures.py
* Connects reanahub/reana-workflow-engine-cwl/issues/90
=> fixtures: renaming field in reana specification cwl fixture.

pytest_reana/version.py, setup.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> release: 0.5.0.dev20190321

pytest_reana/plugin.py, pytest_reana/version.py
* Connects reanahub/reana-job-controller/issues/122
=> plugin: register sample_workflow_workspace fixture

AUTHORS.rst, CHANGES.rst, pytest_reana/version.py, setup.py
=> release: 0.5.0

pytest_reana/fixtures.py, pytest_reana/plugin.py, pytest_reana/version.py, setup.py
* Adresses reanahub/reana-job-controller#147
=> secrets: add new fixtures for secret store

CONTRIBUTING.rst
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
=> docs: waffle -> github projects

pytest_reana/version.py
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
=> version: post-release bump

pytest_reana/fixtures.py, pytest_reana/version.py
=> fixtures: patch db session when creating user

AUTHORS.rst, CHANGES.rst, pytest_reana/fixtures.py, pytest_reana/version.py, setup.py
partially addresses reanahub/reana#348
=> tests: create __reana db schema in app fixture 

pytest_reana/version.py, setup.py
Due to breaking changes in 20.8b0 https://github.com/psf/black/blob/master/CHANGES.md#208b0
=> setup: pin black <20

.flake8, .github/workflows/ci.yml, MANIFEST.in, run-tests.sh, setup.py, tests/test_fixtures.py
addresses https://github.com/reanahub/reana/issues/456
=> ci: added flake8 linter

CHANGES.rst, pytest_reana/version.py, setup.py
Closes reanahub/reana-job-controller#304.
=> installation: upgrade REANA-DB version

pytest_reana/test_utils.py, setup.py
=> setup: remove unused `click` dependency

CHANGES.rst, pytest_reana/fixtures.py, pytest_reana/plugin.py, pytest_reana/version.py, setup.py
closes reanahub/reana-server#358
=> fixtures: added nested Yadage workflow spec 

AUTHORS.rst, pytest_reana/fixtures.py, pytest_reana/version.py
=> fixtures: modify tests to run with the full workspace path stored in the database

CHANGES.rst, pytest_reana/version.py, setup.py
- setup: update to apispec v3
- release: 0.9.1a1
Closes reanahub/reana-commons#399
=> setup: update to apispec v3
