reanahub/pytest-reana

.gitignore
.travis.yml
MANIFEST.in
docs/conf.py
docs/requirements.txt
pytest.ini
reana_pytest_commons/__init__.py
reana_pytest_commons/version.py
run-tests.sh
setup.cfg
setup.py
tests/conftest.py
tests/test_version.py

* Amends license header in all files to the standardised version.
* Fixes license Trove classifier in ``setup.py``.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

global: license header

---

reana_pytest_commons/test_utils.py
setup.py

* ADD utility method to instantiate a SwaggerClient with a mock
http_client, to be used for contract testing of REST APIs.
Closes https://github.com/reanahub/reana/issues/91

utils: addition of make_mock_api_client

---

pytest_reana/fixtures.py
pytest_reana/version.py

* Renames reana_specification workflow spec field to specification,
to match the parsed json format from reana-client.

tests: workflow fixtures specification field

---

pytest_reana/test_utils.py

* Mock api client returns mocked response and mocked http response
instead of only mocked response.
Co-authored-by: Diego Rodriguez diego.rodriguez@cern.ch

utils: mock api client returns both responses

---

pytest_reana/fixtures.py

* Renaming operational_parameters to operational_options.
Connects https://github.com/reanahub/reana-client/issues/200

fixture: renaming operational params to options.

---

pytest_reana/fixtures.py
pytest_reana/version.py

* Updates _BaseConsumerTestIMPL with latest changes in
reana-commons moving to 1 consumer for 1 queue model.
Connects https://github.com/reanahub/reana/issues/119

fixtures: update consumer fixture

---

pytest_reana/fixtures.py
pytest_reana/version.py

fixtures: reana-db objects for session/engine

---

pytest_reana/fixtures.py
pytest_reana/plugin.py
pytest_reana/version.py

* Previously on single test executions the session would be
pointing to the wrong database URI for tests (defautl), causing
the tests to fail.

fixtures: create engine inside app fixture

---

pytest_reana/version.py
setup.py

setup: add upper bound to reana-db 

---

CHANGES.rst
pytest_reana/fixtures.py
pytest_reana/version.py

Closes reanahub/reana-commons#217.

fixtures: shared volume path through env variable

---

pytest_reana/fixtures.py
pytest_reana/version.py

* Creates default resources on `app` fixture.
* Clean `WorkflowResource`s on workflow teardown.
* Closes reanahub/reana-server#296.

fixtures: create/teardown resources 

---

.github/workflows/ci.yml
CHANGES.rst
LICENSE
MANIFEST.in
pytest_reana/version.py
setup.py
tox.ini

Adds support for Python-3.10.
Adds initial Tox configuration to simplify local testing of multiple
Python versions.
Closes reanahub/reana#602.

installation: support for Python-3.10

---

.readthedocs.yaml
MANIFEST.in
docs/conf.py
pytest_reana/fixtures.py
pytest_reana/test_utils.py

Switch to the stable version of kombu's docs, as in the latest one some
references are missing.
Closes https://github.com/reanahub/reana/issues/710.

docs: update readthedocs to v2 and fix kombu references

---

.github/workflows/ci.yml
setup.py

BREAKING CHANGE: drop support for Python 3.6 and 3.7
Closes reanahub/reana#784

build(python): drop support for Python 3.6 and 3.7 (#130)

---

pyproject.toml
run-tests.sh
setup.cfg
setup.py
tox.ini

- **ci(pytest): invoke `pytest` directly instead of `setup.py test` (#133)**
- **build(python): remove deprecated `pytest-runner` (#133)**
- **build(python): add minimal `pyproject.toml` (#133)**
Closes https://github.com/reanahub/reana/issues/814

deprecations setuptools

---

pytest_reana/fixtures.py
pytest_reana/version.py

Closes reanahub/reana-commons#455

fix(fixtures): correctly encode secrets in base64 (#131)

---

setup.py
tox.ini

Fixes `tox` configuration with respect to collecting code coverage information.
Allows higher version of the `coverage` package for Python 3.12 tests.

ci(tox): fix collecting code coverage information (#134)

---

.github/workflows/ci.yml
AUTHORS.md
setup.py
tox.ini

Closes https://github.com/reanahub/reana/issues/837
Add support for Python 3.13.

build(python): add support for Python 3.13 (#136)

---

.github/workflows/ci.yml

Updates CI runners to use Ubuntu 22.04 in the `maint-0.9` branches because 20.04 is not supported anymore. Also removes Python 3.6 from the test matrix because the runners do not support it anymore.

ci(runners): upgrade CI runners to Ubuntu 22.04

---

pytest_reana/fixtures.py

Remove the unused `pkg_resources` import that was not being used anywhere in the code base. Its removal helps to eliminate deprecation warnings.
Closes reanahub/reana-commons#502

refactor(fixtures): remove unused pkg_resources
